# File: /.github/workflows/test.yml

name: Supabase Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Wait for Supabase to be ready
        run: |
          echo "Waiting for Supabase to be ready..."
          # Wait for Supabase to be ready (max 60 seconds)
          timeout 60 bash -c 'until curl -s http://localhost:54321/rest/v1/ > /dev/null; do sleep 1; done'
          echo "Supabase is now ready!"

      - name: Setup test database
        run: |
          # Create test-specific functions
          echo "Setting up test environment..."
          node -e "require('./tests/supabase/test-reset.js').setupTruncateFunction()"
          # Reset and seed test database
          node -e "require('./tests/supabase/test-reset.js').resetTestDatabase()"

      - name: Run unit tests
        run: npm test -- tests/unit

      # Uncomment when ready to run integration tests
      # Note: Integration tests require a running Next.js server
      # - name: Start Next.js server
      #   run: npm run dev & sleep 10
      #
      # - name: Run integration tests
      #   run: npm test -- tests/integration

      - name: Run database structure tests
        run: supabase test db

      - name: Lint SQL with pgTAP
        run: supabase db lint --level=warning
